"""Adds all models

Revision ID: 20c2cb7bb1d0
Revises: 90a24cd47655
Create Date: 2025-01-23 11:50:26.853535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c2cb7bb1d0'
down_revision = '90a24cd47655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('street_address',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
